services:

  database:
    image: "login_system__database"
    build: ./database

    ports:
      - "3307:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
  
  backend:
    depends_on:
      database:
        condition: service_healthy

    image: "login_system__backend"
    build: ./backend

    ports:
      - "8081:8080"
    
    links:
      - database

    